edit:
    pattern:  /admin/edit
    defaults:
      _controller: SillyCMSBundle:Page:edit

save:
    pattern:  /admin/save
    defaults:
      _controller: SillyCMSBundle:Page:save
    
showHome:
    pattern:  /
    defaults: { _controller: SillyCMSBundle:Page:show, slug: '' }

show:
    pattern:  /:slug
    defaults: { _controller: SillyCMSBundle:Page:show }
    requirements: { slug: .* }