edit:
    pattern:  /admin/edit/{slug}
    defaults:
      _controller: SillyCMSBundle:Page:edit

save:
    pattern:  /admin/save
    defaults:
      _controller: SillyCMSBundle:Page:save
    
show:
    pattern:  /{slug}
    defaults: { _controller: SillyCMSBundle:Page:show }
    requirements: { slug: ^.*$ }

fos_user_user_show:
    pattern:  /admin/user/{username}

fos_user_user_update:
    pattern:  /admin/user/{username}/edit

fos_user_user_delete:
    pattern:  /admin/user/{username}/delete