app.config:
    charset:       UTF-8
    error_handler: null
    csrf_secret:   xxxxxxxxxx
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, annotations: true }
    templating:    { engines: ['twig'] }
    session:
        default_locale: en
        lifetime:       3600
        auto_start:     true

security.config:
    providers:
        fos_user_provider:
            password_encoder: sha512
            id: fos_user.user_manager
    firewalls:
        main:
            pattern: .*
            form_login:
                provider:                       fos_user_provider
                login_path:                     /login
                use_forward:                    false
                check_path:                     /login-check
                failure_path:                   null
            logout: true
            anonymous: true
    access_control:
        - { path: "/inbox.*", role: IS_AUTHENTICATED_FULLY }
        - { path: "/.*", role: IS_AUTHENTICATED_ANONYMOUSLY }

fos_user.config:
    db_driver: orm
    provider_key: main
    encoder:
        iterations: 1
        encodeHashAsBase64: true
        algorithm: sha512
    class:
        model:
            user: Application\UserBundle\Entity\User
        form:
            user: FOS\UserBundle\Form\UserForm
        controller:
            user: Application\UserBundle\Controller\UserController
            security: Application\UserBundle\Controller\SecurityController

# Twig Configuration
twig.config:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

extra.config: ~

## Doctrine Configuration
doctrine.dbal:
    dbname:   sillycms
    user:     root
    password: root
doctrine.orm:
    auto_generate_proxy_classes: %kernel.debug%
    mappings:
        SillyCMSBundle: ~
        FOSUserBundle: ~
        UserBundle: ~

## Swiftmailer Configuration
#swiftmailer.config:
#    transport:  smtp
#    encryption: ssl
#    auth_mode:  login
#    host:       smtp.gmail.com
#    username:   xxxxxxxx
#    password:   xxxxxxxx

# Custom services

services:
  twig.extension.WikiText:
       class: Application\SillyCMSBundle\Twig\Extensions\WikiText
       tags:
           - { name: twig.extension }
       arguments:
         - @service_container
