security:
    resource: @FOSUserBundle/Resources/config/routing/security.xml
user:
    resource: @FOSUserBundle/Resources/config/routing/user.xml
SillyCMS:
    resource: @SillyCMSBundle/Resources/config/routing.yml
